name: kti-planner

services:
  web:
    build:
      context: .
      args:
        REDIS_URL: redis://redis
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      EMAIL_IMG_DIR: "/home/node/app/uploads/user-emails"
      MOODLE_BASE_URL: "https://enauczanie.pg.edu.pl/2025/course/view.php?id="
    stop_grace_period: 1s
  postgres:
    build:
      context: ./db
    ports:
      - '5432:5432'
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - '6379:6379'
