name: kti-planner

services:
  web:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      REDIS_URL: redis://redis
  postgres:
    build:
      context: ./db
    env_file:
      - .env
  redis:
    image: redis
