name: Build and test

on: [push, workflow_dispatch]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Setup ENV
        run: |
          cat > .env << EOF
          POSTGRES_USER=CI
          POSTGRES_PASSWORD=CI_PASS
          POSTGRES_DB=kti_planner
          MOODLE_BASE_URL=https://enauczanie.pg.edu.pl/2025/course/view.php?id=
          EOF

      - name: Run app
        run: |
          docker compose up --build -d --wait

      - name: Unit test
        run: npm run test-unit

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: E2E test
        run: npm run test-e2e
